services:
  app:
    build: 
      context: .
    
    expose:
      - "8000"
      - "8501"



  nginx:
    build :
      context: .
      dockerfile: Dockerfile.nginx

    depends_on:
      - app

    ports:
      - "80:80"

