services:
  app:
    build: 
      context: .
    
    ports:
      - ":8000"

    volumes:
      - ./.aws:/root/.aws:ro


  nginx:
    build :
      context: .
      dockerfile: Dockerfile.nginx

    depends_on:
      - app

    ports:
      - "80:80"

